name: pypi
on:
  - workflow_dispatch
env:
  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
jobs:
  package-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs
          poetry config pypi-token.pypi $PYPI_TOKEN
      - name: Deploy to pypi
        run: |
          poetry build
          poetry publish
